package common_constants

var WORKS_ARRAY = []string{
	"Software Engineer",
	"Data Scientist",
	"Product Manager",
	"Project Manager",
	"Business Analyst",
	"DevOps Engineer",
	"Quality Assurance Engineer",
	"UX/UI Designer",
	"Marketing Manager",
	"Sales Executive",
	"Account Manager",
	"Customer Support Specialist",
	"Graphic Designer",
	"Content Writer",
	"Technical Writer",
	"IT Support Specialist",
	"Human Resources Manager",
	"Financial Analyst",
	"Operations Manager",
	"Supply Chain Manager",
	"Network Engineer",
	"System Administrator",
	"Database Administrator",
	"Web Developer",
	"Mobile App Developer",
	"Cloud Architect",
	"Cybersecurity Analyst",
	"SEO Specialist",
	"Copywriter",
	"Creative Director",
	"Product Designer",
	"Machine Learning Engineer",
	"AI Researcher",
	"Blockchain Developer",
	"Game Developer",
	"Video Editor",
	"Photographer",
	"Animator",
	"Interior Designer",
	"Event Planner",
	"Public Relations Specialist",
	"Recruiter",
	"Office Manager",
	"Construction Manager",
	"Electrical Engineer",
	"Mechanical Engineer",
	"Civil Engineer",
	"Architect",
	"Biomedical Engineer",
	"Pharmaceutical Sales Representative",
	"Medical Laboratory Technician",
	"Registered Nurse",
	"Physician Assistant",
	"Physical Therapist",
	"Dentist",
	"Surgeon",
	"Radiologist",
	"Pharmacist",
	"Veterinarian",
	"Nutritionist",
	"Personal Trainer",
	"Chiropractor",
	"Speech-Language Pathologist",
	"Social Worker",
	"Psychologist",
	"Counselor",
	"Legal Assistant",
	"Paralegal",
	"Attorney",
	"Judge",
	"Accountant",
	"Auditor",
	"Tax Consultant",
	"Real Estate Agent",
	"Property Manager",
	"Investment Banker",
	"Financial Planner",
	"Loan Officer",
	"Insurance Agent",
	"Compliance Officer",
	"Risk Manager",
	"Economist",
	"Journalist",
	"News Anchor",
	"Radio Host",
	"Film Director",
	"Producer",
	"Scriptwriter",
	"Art Director",
	"Sound Engineer",
	"Music Producer",
	"Musician",
	"Actor",
	"Dancer",
	"Teacher",
	"Professor",
	"Research Scientist",
	"Librarian",
	"Historian",
	"Archaeologist",
	"Anthropologist",
	"Geologist",
	"Biologist",
	"Chemist",
	"Physicist",
}
